//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQWithWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerTools
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnswerTools()
        {
            this.UserHasToolsNumber = new HashSet<UserHasToolsNumber>();
        }
    
        public int TID { get; set; }
        public string T_Name { get; set; }
        public string T_Desc { get; set; }
        public int T_Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserHasToolsNumber> UserHasToolsNumber { get; set; }
    }
}
