//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQWithWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int ScoreID { get; set; }
        public int S_Correct { get; set; }
        public string S_Achieve_Date { get; set; }
        public int S_GroupID { get; set; }
        public int S_UserID { get; set; }
        public int S_QID { get; set; }
        public string S_Type { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual S_GroupNumber S_GroupNumber { get; set; }
        public virtual Score_Type Score_Type { get; set; }
        public virtual User User { get; set; }
    }
}
