//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQWithWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.LogInfo = new HashSet<LogInfo>();
            this.S_GroupNumber = new HashSet<S_GroupNumber>();
            this.Score = new HashSet<Score>();
            this.UserHasToolsNumber = new HashSet<UserHasToolsNumber>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserNameHash { get; set; }
        public string Passwords { get; set; }
        public string Email { get; set; }
        public int LevelID { get; set; }
        public Nullable<int> Max_score { get; set; }
        public int RoleID { get; set; }
        public string IsOnline { get; set; }
        public string Add_Date { get; set; }
    
        public virtual IsOnline IsOnline1 { get; set; }
        public virtual Level Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogInfo> LogInfo { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_GroupNumber> S_GroupNumber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Score { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserHasToolsNumber> UserHasToolsNumber { get; set; }
    }
}
